import { Injectable } from '@angular/core';

interface BoardStatus {
  [square: string]: {
    occupiedBy: string | null;
    occupiedByType: string | null;
  };
}

@Injectable({
  providedIn: 'root',
})
export class UtilsService {
  public boardStatus: BoardStatus = {
    A8: { occupiedBy: null, occupiedByType: null },
    B8: { occupiedBy: null, occupiedByType: null },
    C8: { occupiedBy: null, occupiedByType: null },
    D8: { occupiedBy: null, occupiedByType: null },
    E8: { occupiedBy: null, occupiedByType: null },
    F8: { occupiedBy: null, occupiedByType: null },
    G8: { occupiedBy: null, occupiedByType: null },
    H8: { occupiedBy: null, occupiedByType: null },

    A7: { occupiedBy: null, occupiedByType: null },
    B7: { occupiedBy: null, occupiedByType: null },
    C7: { occupiedBy: null, occupiedByType: null },
    D7: { occupiedBy: null, occupiedByType: null },
    E7: { occupiedBy: null, occupiedByType: null },
    F7: { occupiedBy: null, occupiedByType: null },
    G7: { occupiedBy: null, occupiedByType: null },
    H7: { occupiedBy: null, occupiedByType: null },

    A6: { occupiedBy: null, occupiedByType: null },
    B6: { occupiedBy: null, occupiedByType: null },
    C6: { occupiedBy: null, occupiedByType: null },
    D6: { occupiedBy: null, occupiedByType: null },
    E6: { occupiedBy: null, occupiedByType: null },
    F6: { occupiedBy: null, occupiedByType: null },
    G6: { occupiedBy: null, occupiedByType: null },
    H6: { occupiedBy: null, occupiedByType: null },

    A5: { occupiedBy: null, occupiedByType: null },
    B5: { occupiedBy: null, occupiedByType: null },
    C5: { occupiedBy: null, occupiedByType: null },
    D5: { occupiedBy: null, occupiedByType: null },
    E5: { occupiedBy: null, occupiedByType: null },
    F5: { occupiedBy: null, occupiedByType: null },
    G5: { occupiedBy: null, occupiedByType: null },
    H5: { occupiedBy: null, occupiedByType: null },

    A4: { occupiedBy: null, occupiedByType: null },
    B4: { occupiedBy: null, occupiedByType: null },
    C4: { occupiedBy: null, occupiedByType: null },
    D4: { occupiedBy: null, occupiedByType: null },
    E4: { occupiedBy: null, occupiedByType: null },
    F4: { occupiedBy: null, occupiedByType: null },
    G4: { occupiedBy: null, occupiedByType: null },
    H4: { occupiedBy: null, occupiedByType: null },

    A3: { occupiedBy: null, occupiedByType: null },
    B3: { occupiedBy: null, occupiedByType: null },
    C3: { occupiedBy: null, occupiedByType: null },
    D3: { occupiedBy: null, occupiedByType: null },
    E3: { occupiedBy: null, occupiedByType: null },
    F3: { occupiedBy: null, occupiedByType: null },
    G3: { occupiedBy: null, occupiedByType: null },
    H3: { occupiedBy: null, occupiedByType: null },

    A2: { occupiedBy: null, occupiedByType: null },
    B2: { occupiedBy: null, occupiedByType: null },
    C2: { occupiedBy: null, occupiedByType: null },
    D2: { occupiedBy: null, occupiedByType: null },
    E2: { occupiedBy: null, occupiedByType: null },
    F2: { occupiedBy: null, occupiedByType: null },
    G2: { occupiedBy: null, occupiedByType: null },
    H2: { occupiedBy: null, occupiedByType: null },

    A1: { occupiedBy: null, occupiedByType: null },
    B1: { occupiedBy: null, occupiedByType: null },
    C1: { occupiedBy: null, occupiedByType: null },
    D1: { occupiedBy: null, occupiedByType: null },
    E1: { occupiedBy: null, occupiedByType: null },
    F1: { occupiedBy: null, occupiedByType: null },
    G1: { occupiedBy: null, occupiedByType: null },
    H1: { occupiedBy: null, occupiedByType: null },
  };

  boardAsWhite = [
    'A8',
    'B8',
    'C8',
    'D8',
    'E8',
    'F8',
    'G8',
    'H8',
    'A7',
    'B7',
    'C7',
    'D7',
    'E7',
    'F7',
    'G7',
    'H7',
    'A6',
    'B6',
    'C6',
    'D6',
    'E6',
    'F6',
    'G6',
    'H6',
    'A5',
    'B5',
    'C5',
    'D5',
    'E5',
    'F5',
    'G5',
    'H5',
    'A4',
    'B4',
    'C4',
    'D4',
    'E4',
    'F4',
    'G4',
    'H4',
    'A3',
    'B3',
    'C3',
    'D3',
    'E3',
    'F3',
    'G3',
    'H3',
    'A2',
    'B2',
    'C2',
    'D2',
    'E2',
    'F2',
    'G2',
    'H2',
    'A1',
    'B1',
    'C1',
    'D1',
    'E1',
    'F1',
    'G1',
    'H1',
  ];

  allPossiblePositions: any = {
    rook: {
      A8: {
        left: [],
        right: ['B8', 'C8', 'D8', 'E8', 'F8', 'G8', 'H8'],
        top: [],
        bottom: ['A7', 'A6', 'A5', 'A4', 'A3', 'A2', 'A1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      B8: {
        left: ['A8'],
        right: ['C8', 'D8', 'E8', 'F8', 'G8', 'H8'],
        top: [],
        bottom: ['B7', 'B6', 'B5', 'B4', 'B3', 'B2', 'B1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      C8: {
        left: ['B8', 'A8'],
        right: ['D8', 'E8', 'F8', 'G8', 'H8'],
        top: [],
        bottom: ['C7', 'C6', 'C5', 'C4', 'C3', 'C2', 'C1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      D8: {
        left: ['C8', 'B8', 'A8'],
        right: ['E8', 'F8', 'G8', 'H8'],
        top: [],
        bottom: ['D7', 'D6', 'D5', 'D4', 'D3', 'D2', 'D1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      E8: {
        left: ['D8', 'C8', 'B8', 'A8'],
        right: ['F8', 'G8', 'H8'],
        top: [],
        bottom: ['E7', 'E6', 'E5', 'E4', 'E3', 'E2', 'E1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      F8: {
        left: ['E8', 'D8', 'C8', 'B8', 'A8'],
        right: ['G8', 'H8'],
        top: [],
        bottom: ['F7', 'F6', 'F5', 'F4', 'F3', 'F2', 'F1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      G8: {
        left: ['F8', 'E8', 'D8', 'C8', 'B8', 'A8'],
        right: ['H8'],
        top: [],
        bottom: ['G7', 'G6', 'G5', 'G4', 'G3', 'G2', 'G1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      H8: {
        left: ['G8', 'F8', 'E8', 'D8', 'C8', 'B8', 'A8'],
        right: [],
        top: [],
        bottom: ['H7', 'H6', 'H5', 'H4', 'H3', 'H2', 'H1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      A7: {
        left: [],
        right: ['B7', 'C7', 'D7', 'E7', 'F7', 'G7', 'H7'],
        top: ['A8'],
        bottom: ['A6', 'A5', 'A4', 'A3', 'A2', 'A1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      B7: {
        left: ['A7'],
        right: ['C7', 'D7', 'E7', 'F7', 'G7', 'H7'],
        top: ['B8'],
        bottom: ['B6', 'B5', 'B4', 'B3', 'B2', 'B1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      C7: {
        left: ['B7', 'A7'],
        right: ['D7', 'E7', 'F7', 'G7', 'H7'],
        top: ['C8'],
        bottom: ['C6', 'C5', 'C4', 'C3', 'C2', 'C1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      D7: {
        left: ['C7', 'B7', 'A7'],
        right: ['E7', 'F7', 'G7', 'H7'],
        top: ['D8'],
        bottom: ['D6', 'D5', 'D4', 'D3', 'D2', 'D1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      E7: {
        left: ['D7', 'C7', 'B7', 'A7'],
        right: ['F7', 'G7', 'H7'],
        top: ['E8'],
        bottom: ['E6', 'E5', 'E4', 'E3', 'E2', 'E1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      F7: {
        left: ['E7', 'D7', 'C7', 'B7', 'A7'],
        right: ['G7', 'H7'],
        top: ['F8'],
        bottom: ['F6', 'F5', 'F4', 'F3', 'F2', 'F1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      G7: {
        left: ['F7', 'E7', 'D7', 'C7', 'B7', 'A7'],
        right: ['H7'],
        top: ['G8'],
        bottom: ['G6', 'G5', 'G4', 'G3', 'G2', 'G1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      H7: {
        left: ['G7', 'F7', 'E7', 'D7', 'C7', 'B7', 'A7'],
        right: [],
        top: ['H8'],
        bottom: ['H6', 'H5', 'H4', 'H3', 'H2', 'H1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      A6: {
        left: [],
        right: ['B6', 'C6', 'D6', 'E6', 'F6', 'G6', 'H6'],
        top: ['A7', 'A8'],
        bottom: ['A5', 'A4', 'A3', 'A2', 'A1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      B6: {
        left: ['A6'],
        right: ['C6', 'D6', 'E6', 'F6', 'G6', 'H6'],
        top: ['B7', 'B8'],
        bottom: ['B5', 'B4', 'B3', 'B2', 'B1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      C6: {
        left: ['B6', 'A6'],
        right: ['D6', 'E6', 'F6', 'G6', 'H6'],
        top: ['C7', 'C8'],
        bottom: ['C5', 'C4', 'C3', 'C2', 'C1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      D6: {
        left: ['C6', 'B6', 'A6'],
        right: ['E6', 'F6', 'G6', 'H6'],
        top: ['D7', 'D8'],
        bottom: ['D5', 'D4', 'D3', 'D2', 'D1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      E6: {
        left: ['D6', 'C6', 'B6', 'A6'],
        right: ['F6', 'G6', 'H6'],
        top: ['E7', 'E8'],
        bottom: ['E5', 'E4', 'E3', 'E2', 'E1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      F6: {
        left: ['E6', 'D6', 'C6', 'B6', 'A6'],
        right: ['G6', 'H6'],
        top: ['F7', 'F8'],
        bottom: ['F5', 'F4', 'F3', 'F2', 'F1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      G6: {
        left: ['F6', 'E6', 'D6', 'C6', 'B6', 'A6'],
        right: ['H6'],
        top: ['G7', 'G8'],
        bottom: ['G5', 'G4', 'G3', 'G2', 'G1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      H6: {
        left: ['G6', 'F6', 'E6', 'D6', 'C6', 'B6', 'A6'],
        right: [],
        top: ['H7', 'H8'],
        bottom: ['H5', 'H4', 'H3', 'H2', 'H1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      A5: {
        left: [],
        right: ['B5', 'C5', 'D5', 'E5', 'F5', 'G5', 'H5'],
        top: ['A6', 'A7', 'A8'],
        bottom: ['A4', 'A3', 'A2', 'A1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      B5: {
        left: ['A5'],
        right: ['C5', 'D5', 'E5', 'F5', 'G5', 'H5'],
        top: ['B6', 'B7', 'B8'],
        bottom: ['B4', 'B3', 'B2', 'B1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      C5: {
        left: ['B5', 'A5'],
        right: ['D5', 'E5', 'F5', 'G5', 'H5'],
        top: ['C6', 'C7', 'C8'],
        bottom: ['C4', 'C3', 'C2', 'C1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      D5: {
        left: ['C5', 'B5', 'A5'],
        right: ['E5', 'F5', 'G5', 'H5'],
        top: ['D6', 'D7', 'D8'],
        bottom: ['D4', 'D3', 'D2', 'D1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      E5: {
        left: ['D5', 'C5', 'B5', 'A5'],
        right: ['F5', 'G5', 'H5'],
        top: ['E6', 'E7', 'E8'],
        bottom: ['E4', 'E3', 'E2', 'E1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      F5: {
        left: ['E5', 'D5', 'C5', 'B5', 'A5'],
        right: ['G5', 'H5'],
        top: ['F6', 'F7', 'F8'],
        bottom: ['F4', 'F3', 'F2', 'F1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      G5: {
        left: ['F5', 'E5', 'D5', 'C5', 'B5', 'A5'],
        right: ['H5'],
        top: ['G6', 'G7', 'G8'],
        bottom: ['G4', 'G3', 'G2', 'G1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      H5: {
        left: ['G5', 'F5', 'E5', 'D5', 'C5', 'B5', 'A5'],
        right: [],
        top: ['H6', 'H7', 'H8'],
        bottom: ['H4', 'H3', 'H2', 'H1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      A4: {
        left: [],
        right: ['B4', 'C4', 'D4', 'E4', 'F4', 'G4', 'H4'],
        top: ['A5', 'A6', 'A7', 'A8'],
        bottom: ['A3', 'A2', 'A1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      B4: {
        left: ['A4'],
        right: ['C4', 'D4', 'E4', 'F4', 'G4', 'H4'],
        top: ['B5', 'B6', 'B7', 'B8'],
        bottom: ['B3', 'B2', 'B1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      C4: {
        left: ['B4', 'A4'],
        right: ['D4', 'E4', 'F4', 'G4', 'H4'],
        top: ['C5', 'C6', 'C7', 'C8'],
        bottom: ['C3', 'C2', 'C1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      D4: {
        left: ['C4', 'B4', 'A4'],
        right: ['E4', 'F4', 'G4', 'H4'],
        top: ['D5', 'D6', 'D7', 'D8'],
        bottom: ['D3', 'D2', 'D1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      E4: {
        left: ['D4', 'C4', 'B4', 'A4'],
        right: ['F4', 'G4', 'H4'],
        top: ['E5', 'E6', 'E7', 'E8'],
        bottom: ['E3', 'E2', 'E1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      F4: {
        left: ['E4', 'D4', 'C4', 'B4', 'A4'],
        right: ['G4', 'H4'],
        top: ['F5', 'F6', 'F7', 'F8'],
        bottom: ['F3', 'F2', 'F1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      G4: {
        left: ['F4', 'E4', 'D4', 'C4', 'B4', 'A4'],
        right: ['H4'],
        top: ['G5', 'G6', 'G7', 'G8'],
        bottom: ['G3', 'G2', 'G1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      H4: {
        left: ['G4', 'F4', 'E4', 'D4', 'C4', 'B4', 'A4'],
        right: [],
        top: ['H5', 'H6', 'H7', 'H8'],
        bottom: ['H3', 'H2', 'H1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      A3: {
        left: [],
        right: ['B3', 'C3', 'D3', 'E3', 'F3', 'G3', 'H3'],
        top: ['A4', 'A5', 'A6', 'A7', 'A8'],
        bottom: ['A2', 'A1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      B3: {
        left: ['A3'],
        right: ['C3', 'D3', 'E3', 'F3', 'G3', 'H3'],
        top: ['B4', 'B5', 'B6', 'B7', 'B8'],
        bottom: ['B2', 'B1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      C3: {
        left: ['B3', 'A3'],
        right: ['D3', 'E3', 'F3', 'G3', 'H3'],
        top: ['C4', 'C5', 'C6', 'C7', 'C8'],
        bottom: ['C2', 'C1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      D3: {
        left: ['C3', 'B3', 'A3'],
        right: ['E3', 'F3', 'G3', 'H3'],
        top: ['D4', 'D5', 'D6', 'D7', 'D8'],
        bottom: ['D2', 'D1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      E3: {
        left: ['D3', 'C3', 'B3', 'A3'],
        right: ['F3', 'G3', 'H3'],
        top: ['E4', 'E5', 'E6', 'E7', 'E8'],
        bottom: ['E2', 'E1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      F3: {
        left: ['E3', 'D3', 'C3', 'B3', 'A3'],
        right: ['G3', 'H3'],
        top: ['F4', 'F5', 'F6', 'F7', 'F8'],
        bottom: ['F2', 'F1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      G3: {
        left: ['F3', 'E3', 'D3', 'C3', 'B3', 'A3'],
        right: ['H3'],
        top: ['G4', 'G5', 'G6', 'G7', 'G8'],
        bottom: ['G2', 'G1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      H3: {
        left: ['G3', 'F3', 'E3', 'D3', 'C3', 'B3', 'A3'],
        right: [],
        top: ['H4', 'H5', 'H6', 'H7', 'H8'],
        bottom: ['H2', 'H1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      A2: {
        left: [],
        right: ['B2', 'C2', 'D2', 'E2', 'F2', 'G2', 'H2'],
        top: ['A3', 'A4', 'A5', 'A6', 'A7', 'A8'],
        bottom: ['A1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      B2: {
        left: ['A2'],
        right: ['C2', 'D2', 'E2', 'F2', 'G2', 'H2'],
        top: ['B3', 'B4', 'B5', 'B6', 'B7', 'B8'],
        bottom: ['B1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      C2: {
        left: ['B2', 'A2'],
        right: ['D2', 'E2', 'F2', 'G2', 'H2'],
        top: ['C3', 'C4', 'C5', 'C6', 'C7', 'C8'],
        bottom: ['C1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      D2: {
        left: ['C2', 'B2', 'A2'],
        right: ['E2', 'F2', 'G2', 'H2'],
        top: ['D3', 'D4', 'D5', 'D6', 'D7', 'D8'],
        bottom: ['D1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      E2: {
        left: ['D2', 'C2', 'B2', 'A2'],
        right: ['F2', 'G2', 'H2'],
        top: ['E3', 'E4', 'E5', 'E6', 'E7', 'E8'],
        bottom: ['E1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      F2: {
        left: ['E2', 'D2', 'C2', 'B2', 'A2'],
        right: ['G2', 'H2'],
        top: ['F3', 'F4', 'F5', 'F6', 'F7', 'F8'],
        bottom: ['F1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      G2: {
        left: ['F2', 'E2', 'D2', 'C2', 'B2', 'A2'],
        right: ['H2'],
        top: ['G3', 'G4', 'G5', 'G6', 'G7', 'G8'],
        bottom: ['G1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      H2: {
        left: ['G2', 'F2', 'E2', 'D2', 'C2', 'B2', 'A2'],
        right: [],
        top: ['H3', 'H4', 'H5', 'H6', 'H7', 'H8'],
        bottom: ['H1'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      A1: {
        left: [],
        right: ['B1', 'C1', 'D1', 'E1', 'F1', 'G1', 'H1'],
        top: ['A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8'],
        bottom: [],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      B1: {
        left: ['A1'],
        right: ['C1', 'D1', 'E1', 'F1', 'G1', 'H1'],
        top: ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8'],
        bottom: [],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      C1: {
        left: ['B1', 'A1'],
        right: ['D1', 'E1', 'F1', 'G1', 'H1'],
        top: ['C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8'],
        bottom: [],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      D1: {
        left: ['C1', 'B1', 'A1'],
        right: ['E1', 'F1', 'G1', 'H1'],
        top: ['D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8'],
        bottom: [],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      E1: {
        left: ['D1', 'C1', 'B1', 'A1'],
        right: ['F1', 'G1', 'H1'],
        top: ['E2', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8'],
        bottom: [],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      F1: {
        left: ['E1', 'D1', 'C1', 'B1', 'A1'],
        right: ['G1', 'H1'],
        top: ['F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8'],
        bottom: [],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      G1: {
        left: ['F1', 'E1', 'D1', 'C1', 'B1', 'A1'],
        right: ['H1'],
        top: ['G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8'],
        bottom: [],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
      H1: {
        left: ['G1', 'F1', 'E1', 'D1', 'C1', 'B1', 'A1'],
        right: [],
        top: ['H2', 'H3', 'H4', 'H5', 'H6', 'H7', 'H8'],
        bottom: [],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
    },
    bishop: {
      A8: {
        leftTop: [],
        topRight: [],
        rightBottom: ['B7', 'C6', 'D5', 'E4', 'F3', 'G2', 'H1'],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      B8: {
        leftTop: [],
        topRight: [],
        rightBottom: ['C7', 'D6', 'E5', 'F4', 'G3', 'H2'],
        bottomLeft: ['A7'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      C8: {
        leftTop: [],
        topRight: [],
        rightBottom: ['D7', 'E6', 'F5', 'G4', 'H3'],
        bottomLeft: ['B7', 'A6'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      D8: {
        leftTop: [],
        topRight: [],
        rightBottom: ['E7', 'F6', 'G5', 'H4'],
        bottomLeft: ['C7', 'B6', 'A5'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      E8: {
        leftTop: [],
        topRight: [],
        rightBottom: ['F7', 'G6', 'H5'],
        bottomLeft: ['D7', 'C6', 'B5', 'A4'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      F8: {
        leftTop: [],
        topRight: [],
        rightBottom: ['G7', 'H6'],
        bottomLeft: ['E7', 'D6', 'C5', 'B4', 'A3'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      G8: {
        leftTop: [],
        topRight: [],
        rightBottom: ['H7'],
        bottomLeft: ['F7', 'E6', 'D5', 'C4', 'B3', 'A2'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      H8: {
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: ['G7', 'F6', 'E5', 'D4', 'C3', 'B2', 'A1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      A7: {
        leftTop: [],
        topRight: ['B8'],
        rightBottom: ['B6', 'C5', 'D4', 'E3', 'F2', 'G1'],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      B7: {
        leftTop: ['A8'],
        topRight: ['C8'],
        rightBottom: ['C6', 'D5', 'E4', 'F3', 'G2', 'H1'],
        bottomLeft: ['A6'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      C7: {
        leftTop: ['B8'],
        topRight: ['D8'],
        rightBottom: ['D6', 'E5', 'F4', 'G3', 'H2'],
        bottomLeft: ['B6', 'A5'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      D7: {
        leftTop: ['C8'],
        topRight: ['E8'],
        rightBottom: ['E6', 'F5', 'G4', 'H3'],
        bottomLeft: ['C6', 'B5', 'A4'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      E7: {
        leftTop: ['D8'],
        topRight: ['F8'],
        rightBottom: ['F6', 'G5', 'H4'],
        bottomLeft: ['D6', 'C5', 'B4', 'A3'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      F7: {
        leftTop: ['E8'],
        topRight: ['G8'],
        rightBottom: ['G6', 'H5'],
        bottomLeft: ['E6', 'D5', 'C4', 'B3', 'A2'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      G7: {
        leftTop: ['F8'],
        topRight: ['H8'],
        rightBottom: ['H6'],
        bottomLeft: ['F6', 'E5', 'D4', 'C3', 'B2', 'A1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      H7: {
        leftTop: ['G8'],
        topRight: [],
        rightBottom: [],
        bottomLeft: ['G6', 'F5', 'E4', 'D3', 'C2', 'B1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      A6: {
        leftTop: [],
        topRight: ['B7', 'C8'],
        rightBottom: ['B5', 'C4', 'D3', 'E2', 'F1'],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      B6: {
        leftTop: ['A7'],
        topRight: ['C7', 'D8'],
        rightBottom: ['C5', 'D4', 'E3', 'F2', 'G1'],
        bottomLeft: ['A5'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      C6: {
        leftTop: ['B7', 'A8'],
        topRight: ['D7', 'E8'],
        rightBottom: ['D5', 'E4', 'F3', 'G2', 'H1'],
        bottomLeft: ['B5', 'A4'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      D6: {
        leftTop: ['C7', 'B8'],
        topRight: ['E7', 'F8'],
        rightBottom: ['E5', 'F4', 'G3', 'H2'],
        bottomLeft: ['C5', 'B4', 'A3'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      E6: {
        leftTop: ['D7', 'C8'],
        topRight: ['F7', 'G8'],
        rightBottom: ['F5', 'G4', 'H3'],
        bottomLeft: ['D5', 'C4', 'B3', 'A2'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      F6: {
        leftTop: ['E7', 'D8'],
        topRight: ['G7', 'H8'],
        rightBottom: ['G5', 'H4'],
        bottomLeft: ['E5', 'D4', 'C3', 'B2', 'A1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      G6: {
        leftTop: ['F7', 'E8'],
        topRight: ['H7'],
        rightBottom: ['H5'],
        bottomLeft: ['F5', 'E4', 'D3', 'C2', 'B1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      H6: {
        leftTop: ['G7', 'F8'],
        topRight: [],
        rightBottom: [],
        bottomLeft: ['G5', 'F4', 'E3', 'D2', 'C1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      A5: {
        leftTop: [],
        topRight: ['B6', 'C7', 'D8'],
        rightBottom: ['B4', 'C3', 'D2', 'E1'],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      B5: {
        leftTop: ['A6'],
        topRight: ['C6', 'D7', 'E8'],
        rightBottom: ['C4', 'D3', 'E2', 'F1'],
        bottomLeft: ['A4'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      C5: {
        leftTop: ['B6', 'A7'],
        topRight: ['D6', 'E7', 'F8'],
        rightBottom: ['D4', 'E3', 'F2', 'G1'],
        bottomLeft: ['B4', 'A3'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      D5: {
        leftTop: ['C6', 'B7', 'A8'],
        topRight: ['E6', 'F7', 'G8'],
        rightBottom: ['E4', 'F3', 'G2', 'H1'],
        bottomLeft: ['C4', 'B3', 'A2'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      E5: {
        leftTop: ['D6', 'C7', 'B8'],
        topRight: ['F6', 'G7', 'H8'],
        rightBottom: ['F4', 'G3', 'H2'],
        bottomLeft: ['D4', 'C3', 'B2', 'A1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      F5: {
        leftTop: ['E6', 'D7', 'C8'],
        topRight: ['G6', 'H7'],
        rightBottom: ['G4', 'H3'],
        bottomLeft: ['E4', 'D3', 'C2', 'B1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      G5: {
        leftTop: ['F6', 'E7', 'D8'],
        topRight: ['H6'],
        rightBottom: ['H4'],
        bottomLeft: ['F4', 'E3', 'D2', 'C1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      H5: {
        leftTop: ['G6', 'F7', 'E8'],
        topRight: [],
        rightBottom: [],
        bottomLeft: ['G4', 'F3', 'E2', 'D1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      A4: {
        leftTop: [],
        topRight: ['B5', 'C6', 'D7', 'E8'],
        rightBottom: ['B3', 'C2', 'D1'],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      B4: {
        leftTop: ['A5'],
        topRight: ['C5', 'D6', 'E7', 'F8'],
        rightBottom: ['C3', 'D2', 'E1'],
        bottomLeft: ['A3'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      C4: {
        leftTop: ['B5', 'A6'],
        topRight: ['D5', 'E6', 'F7', 'G8'],
        rightBottom: ['D3', 'E2', 'F1'],
        bottomLeft: ['B3', 'A2'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      D4: {
        leftTop: ['C5', 'B6', 'A7'],
        topRight: ['E5', 'F6', 'G7', 'H8'],
        rightBottom: ['E3', 'F2', 'G1'],
        bottomLeft: ['C3', 'B2', 'A1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      E4: {
        leftTop: ['D5', 'C6', 'B7', 'A8'],
        topRight: ['F5', 'G6', 'H7'],
        rightBottom: ['F3', 'G2', 'H1'],
        bottomLeft: ['D3', 'C2', 'B1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      F4: {
        leftTop: ['E5', 'D6', 'C7', 'B8'],
        topRight: ['G5', 'H6'],
        rightBottom: ['G3', 'H2'],
        bottomLeft: ['E3', 'D2', 'C1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      G4: {
        leftTop: ['F5', 'E6', 'D7', 'C8'],
        topRight: ['H5'],
        rightBottom: ['H3'],
        bottomLeft: ['F3', 'E2', 'D1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      H4: {
        leftTop: ['G5', 'F6', 'E7', 'D8'],
        topRight: [],
        rightBottom: [],
        bottomLeft: ['G3', 'F2', 'E1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      A3: {
        leftTop: [],
        topRight: ['B4', 'C5', 'D6', 'E7', 'F8'],
        rightBottom: ['B2', 'C1'],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      B3: {
        leftTop: ['A4'],
        topRight: ['C4', 'D5', 'E6', 'F7', 'G8'],
        rightBottom: ['C2', 'D1'],
        bottomLeft: ['A2'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      C3: {
        leftTop: ['B4', 'A5'],
        topRight: ['D4', 'E5', 'F6', 'G7', 'H8'],
        rightBottom: ['D2', 'E1'],
        bottomLeft: ['B2', 'A1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      D3: {
        leftTop: ['C4', 'B5', 'A6'],
        topRight: ['E4', 'F5', 'G6', 'H7'],
        rightBottom: ['E2', 'F1'],
        bottomLeft: ['C2', 'B1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      E3: {
        leftTop: ['D4', 'C5', 'B6', 'A7'],
        topRight: ['F4', 'G5', 'H6'],
        rightBottom: ['F2', 'G1'],
        bottomLeft: ['D2', 'C1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      F3: {
        leftTop: ['E4', 'D5', 'C6', 'B7', 'A8'],
        topRight: ['G4', 'H5'],
        rightBottom: ['G2', 'H1'],
        bottomLeft: ['E2', 'D1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      G3: {
        leftTop: ['F4', 'E5', 'D6', 'C7', 'B8'],
        topRight: ['H4'],
        rightBottom: ['H2'],
        bottomLeft: ['F2', 'E1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      H3: {
        leftTop: ['G4', 'F5', 'E6', 'D7', 'C8'],
        topRight: [],
        rightBottom: [],
        bottomLeft: ['G2', 'F1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      A2: {
        leftTop: [],
        topRight: ['B3', 'C4', 'D5', 'E6', 'F7', 'G8'],
        rightBottom: ['B1'],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      B2: {
        leftTop: ['A3'],
        topRight: ['C3', 'D4', 'E5', 'F6', 'G7', 'H8'],
        rightBottom: ['C1'],
        bottomLeft: ['A1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      C2: {
        leftTop: ['B3', 'A4'],
        topRight: ['D3', 'E4', 'F5', 'G6', 'H7'],
        rightBottom: ['D1'],
        bottomLeft: ['B1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      D2: {
        leftTop: ['C3', 'B4', 'A5'],
        topRight: ['E3', 'F4', 'G5', 'H6'],
        rightBottom: ['E1'],
        bottomLeft: ['C1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      E2: {
        leftTop: ['D3', 'C4', 'B5', 'A6'],
        topRight: ['F3', 'G4', 'H5'],
        rightBottom: ['F1'],
        bottomLeft: ['D1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      F2: {
        leftTop: ['E3', 'D4', 'C5', 'B6', 'A7'],
        topRight: ['G3', 'H4'],
        rightBottom: ['G1'],
        bottomLeft: ['E1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      G2: {
        leftTop: ['F3', 'E4', 'D5', 'C6', 'B7', 'A8'],
        topRight: ['H3'],
        rightBottom: ['H1'],
        bottomLeft: ['F1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      H2: {
        leftTop: ['G3', 'F4', 'E5', 'D6', 'C7', 'B8'],
        topRight: [],
        rightBottom: [],
        bottomLeft: ['G1'],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      A1: {
        leftTop: [],
        topRight: ['B2', 'C3', 'D4', 'E5', 'F6', 'G7', 'H8'],
        rightBottom: [],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      B1: {
        leftTop: ['A2'],
        topRight: ['C2', 'D3', 'E4', 'F5', 'G6', 'H7'],
        rightBottom: [],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      C1: {
        leftTop: ['B2', 'A3'],
        topRight: ['D2', 'E3', 'F4', 'G5', 'H6'],
        rightBottom: [],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      D1: {
        leftTop: ['C2', 'B3', 'A4'],
        topRight: ['E2', 'F3', 'G4', 'H5'],
        rightBottom: [],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      E1: {
        leftTop: ['D2', 'C3', 'B4', 'A5'],
        topRight: ['F2', 'G3', 'H4'],
        rightBottom: [],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      F1: {
        leftTop: ['E2', 'D3', 'C4', 'B5', 'A6'],
        topRight: ['G2', 'H3'],
        rightBottom: [],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      G1: {
        leftTop: ['F2', 'E3', 'D4', 'C5', 'B6', 'A7'],
        topRight: ['H2'],
        rightBottom: [],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
      H1: {
        leftTop: ['G2', 'F3', 'E4', 'D5', 'C6', 'B7', 'A8'],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
        left: [],
        right: [],
        top: [],
        bottom: [],
      },
    },
    queen: {
      A8: {
        bottom: ['A7', 'A6', 'A5', 'A4', 'A3', 'A2', 'A1'],
        left: [],
        right: ['B8', 'C8', 'D8', 'E8', 'F8', 'G8', 'H8'],
        bottomLeft: [],
        rightBottom: ['B7', 'C6', 'D5', 'E4', 'F3', 'G2', 'H1'],
        top: [],
        leftTop: [],
        topRight: [],
      },
      B8: {
        bottom: ['B7', 'B6', 'B5', 'B4', 'B3', 'B2', 'B1'],
        left: ['A8'],
        right: ['C8', 'D8', 'E8', 'F8', 'G8', 'H8'],
        bottomLeft: ['A7'],
        rightBottom: ['C7', 'D6', 'E5', 'F4', 'G3', 'H2'],
        top: [],
        leftTop: [],
        topRight: [],
      },
      C8: {
        bottom: ['C7', 'C6', 'C5', 'C4', 'C3', 'C2', 'C1'],
        left: ['B8', 'A8'],
        right: ['D8', 'E8', 'F8', 'G8', 'H8'],
        bottomLeft: ['B7', 'A6'],
        rightBottom: ['D7', 'E6', 'F5', 'G4', 'H3'],
        top: [],
        leftTop: [],
        topRight: [],
      },
      D8: {
        bottom: ['D7', 'D6', 'D5', 'D4', 'D3', 'D2', 'D1'],
        left: ['C8', 'B8', 'A8'],
        right: ['E8', 'F8', 'G8', 'H8'],
        bottomLeft: ['C7', 'B6', 'A5'],
        rightBottom: ['E7', 'F6', 'G5', 'H4'],
        top: [],
        leftTop: [],
        topRight: [],
      },
      E8: {
        bottom: ['E7', 'E6', 'E5', 'E4', 'E3', 'E2', 'E1'],
        left: ['D8', 'C8', 'B8', 'A8'],
        right: ['F8', 'G8', 'H8'],
        bottomLeft: ['D7', 'C6', 'B5', 'A4'],
        rightBottom: ['F7', 'G6', 'H5'],
        top: [],
        leftTop: [],
        topRight: [],
      },
      F8: {
        bottom: ['F7', 'F6', 'F5', 'F4', 'F3', 'F2', 'F1'],
        left: ['E8', 'D8', 'C8', 'B8', 'A8'],
        right: ['G8', 'H8'],
        bottomLeft: ['E7', 'D6', 'C5', 'B4', 'A3'],
        rightBottom: ['G7', 'H6'],
        top: [],
        leftTop: [],
        topRight: [],
      },
      G8: {
        bottom: ['G7', 'G6', 'G5', 'G4', 'G3', 'G2', 'G1'],
        left: ['F8', 'E8', 'D8', 'C8', 'B8', 'A8'],
        right: ['H8'],
        bottomLeft: ['F7', 'E6', 'D5', 'C4', 'B3', 'A2'],
        rightBottom: ['H7'],
        top: [],
        leftTop: [],
        topRight: [],
      },
      H8: {
        bottom: ['H7', 'H6', 'H5', 'H4', 'H3', 'H2', 'H1'],
        left: ['G8', 'F8', 'E8', 'D8', 'C8', 'B8', 'A8'],
        right: [],
        bottomLeft: ['G7', 'F6', 'E5', 'D4', 'C3', 'B2', 'A1'],
        rightBottom: [],
        top: [],
        leftTop: [],
        topRight: [],
      },
      A7: {
        bottom: ['A6', 'A5', 'A4', 'A3', 'A2', 'A1'],
        left: [],
        right: ['B7', 'C7', 'D7', 'E7', 'F7', 'G7', 'H7'],
        bottomLeft: [],
        rightBottom: ['B6', 'C5', 'D4', 'E3', 'F2', 'G1'],
        top: ['A8'],
        leftTop: [],
        topRight: ['B8'],
      },
      B7: {
        bottom: ['B6', 'B5', 'B4', 'B3', 'B2', 'B1'],
        left: ['A7'],
        right: ['C7', 'D7', 'E7', 'F7', 'G7', 'H7'],
        bottomLeft: ['A6'],
        rightBottom: ['C6', 'D5', 'E4', 'F3', 'G2', 'H1'],
        top: ['B8'],
        leftTop: ['A8'],
        topRight: ['C8'],
      },
      C7: {
        bottom: ['C6', 'C5', 'C4', 'C3', 'C2', 'C1'],
        left: ['B7', 'A7'],
        right: ['D7', 'E7', 'F7', 'G7', 'H7'],
        bottomLeft: ['B6', 'A5'],
        rightBottom: ['D6', 'E5', 'F4', 'G3', 'H2'],
        top: ['C8'],
        leftTop: ['B8'],
        topRight: ['D8'],
      },
      D7: {
        bottom: ['D6', 'D5', 'D4', 'D3', 'D2', 'D1'],
        left: ['C7', 'B7', 'A7'],
        right: ['E7', 'F7', 'G7', 'H7'],
        bottomLeft: ['C6', 'B5', 'A4'],
        rightBottom: ['E6', 'F5', 'G4', 'H3'],
        top: ['D8'],
        leftTop: ['C8'],
        topRight: ['E8'],
      },
      E7: {
        bottom: ['E6', 'E5', 'E4', 'E3', 'E2', 'E1'],
        left: ['D7', 'C7', 'B7', 'A7'],
        right: ['F7', 'G7', 'H7'],
        bottomLeft: ['D6', 'C5', 'B4', 'A3'],
        rightBottom: ['F6', 'G5', 'H4'],
        top: ['E8'],
        leftTop: ['D8'],
        topRight: ['F8'],
      },
      F7: {
        bottom: ['F6', 'F5', 'F4', 'F3', 'F2', 'F1'],
        left: ['E7', 'D7', 'C7', 'B7', 'A7'],
        right: ['G7', 'H7'],
        bottomLeft: ['E6', 'D5', 'C4', 'B3', 'A2'],
        rightBottom: ['G6', 'H5'],
        top: ['F8'],
        leftTop: ['E8'],
        topRight: ['G8'],
      },
      G7: {
        bottom: ['G6', 'G5', 'G4', 'G3', 'G2', 'G1'],
        left: ['F7', 'E7', 'D7', 'C7', 'B7', 'A7'],
        right: ['H7'],
        bottomLeft: ['F6', 'E5', 'D4', 'C3', 'B2', 'A1'],
        rightBottom: ['H6'],
        top: ['G8'],
        leftTop: ['F8'],
        topRight: ['H8'],
      },
      H7: {
        bottom: ['H6', 'H5', 'H4', 'H3', 'H2', 'H1'],
        left: ['G7', 'F7', 'E7', 'D7', 'C7', 'B7', 'A7'],
        right: [],
        bottomLeft: ['G6', 'F5', 'E4', 'D3', 'C2', 'B1'],
        rightBottom: [],
        top: ['H8'],
        leftTop: ['G8'],
        topRight: [],
      },
      A6: {
        bottom: ['A5', 'A4', 'A3', 'A2', 'A1'],
        left: [],
        right: ['B6', 'C6', 'D6', 'E6', 'F6', 'G6', 'H6'],
        bottomLeft: [],
        rightBottom: ['B5', 'C4', 'D3', 'E2', 'F1'],
        top: ['A7', 'A8'],
        leftTop: [],
        topRight: ['B7', 'C8'],
      },
      B6: {
        bottom: ['B5', 'B4', 'B3', 'B2', 'B1'],
        left: ['A6'],
        right: ['C6', 'D6', 'E6', 'F6', 'G6', 'H6'],
        bottomLeft: ['A5'],
        rightBottom: ['C5', 'D4', 'E3', 'F2', 'G1'],
        top: ['B7', 'B8'],
        leftTop: ['A7'],
        topRight: ['C7', 'D8'],
      },
      C6: {
        bottom: ['C5', 'C4', 'C3', 'C2', 'C1'],
        left: ['B6', 'A6'],
        right: ['D6', 'E6', 'F6', 'G6', 'H6'],
        bottomLeft: ['B5', 'A4'],
        rightBottom: ['D5', 'E4', 'F3', 'G2', 'H1'],
        top: ['C7', 'C8'],
        leftTop: ['B7', 'A8'],
        topRight: ['D7', 'E8'],
      },
      D6: {
        bottom: ['D5', 'D4', 'D3', 'D2', 'D1'],
        left: ['C6', 'B6', 'A6'],
        right: ['E6', 'F6', 'G6', 'H6'],
        bottomLeft: ['C5', 'B4', 'A3'],
        rightBottom: ['E5', 'F4', 'G3', 'H2'],
        top: ['D7', 'D8'],
        leftTop: ['C7', 'B8'],
        topRight: ['E7', 'F8'],
      },
      E6: {
        bottom: ['E5', 'E4', 'E3', 'E2', 'E1'],
        left: ['D6', 'C6', 'B6', 'A6'],
        right: ['F6', 'G6', 'H6'],
        bottomLeft: ['D5', 'C4', 'B3', 'A2'],
        rightBottom: ['F5', 'G4', 'H3'],
        top: ['E7', 'E8'],
        leftTop: ['D7', 'C8'],
        topRight: ['F7', 'G8'],
      },
      F6: {
        bottom: ['F5', 'F4', 'F3', 'F2', 'F1'],
        left: ['E6', 'D6', 'C6', 'B6', 'A6'],
        right: ['G6', 'H6'],
        bottomLeft: ['E5', 'D4', 'C3', 'B2', 'A1'],
        rightBottom: ['G5', 'H4'],
        top: ['F7', 'F8'],
        leftTop: ['E7', 'D8'],
        topRight: ['G7', 'H8'],
      },
      G6: {
        bottom: ['G5', 'G4', 'G3', 'G2', 'G1'],
        left: ['F6', 'E6', 'D6', 'C6', 'B6', 'A6'],
        right: ['H6'],
        bottomLeft: ['F5', 'E4', 'D3', 'C2', 'B1'],
        rightBottom: ['H5'],
        top: ['G7', 'G8'],
        leftTop: ['F7', 'E8'],
        topRight: ['H7'],
      },
      H6: {
        bottom: ['H5', 'H4', 'H3', 'H2', 'H1'],
        left: ['G6', 'F6', 'E6', 'D6', 'C6', 'B6', 'A6'],
        right: [],
        bottomLeft: ['G5', 'F4', 'E3', 'D2', 'C1'],
        rightBottom: [],
        top: ['H7', 'H8'],
        leftTop: ['G7', 'F8'],
        topRight: [],
      },
      A5: {
        bottom: ['A4', 'A3', 'A2', 'A1'],
        left: [],
        right: ['B5', 'C5', 'D5', 'E5', 'F5', 'G5', 'H5'],
        bottomLeft: [],
        rightBottom: ['B4', 'C3', 'D2', 'E1'],
        top: ['A6', 'A7', 'A8'],
        leftTop: [],
        topRight: ['B6', 'C7', 'D8'],
      },
      B5: {
        bottom: ['B4', 'B3', 'B2', 'B1'],
        left: ['A5'],
        right: ['C5', 'D5', 'E5', 'F5', 'G5', 'H5'],
        bottomLeft: ['A4'],
        rightBottom: ['C4', 'D3', 'E2', 'F1'],
        top: ['B6', 'B7', 'B8'],
        leftTop: ['A6'],
        topRight: ['C6', 'D7', 'E8'],
      },
      C5: {
        bottom: ['C4', 'C3', 'C2', 'C1'],
        left: ['B5', 'A5'],
        right: ['D5', 'E5', 'F5', 'G5', 'H5'],
        bottomLeft: ['B4', 'A3'],
        rightBottom: ['D4', 'E3', 'F2', 'G1'],
        top: ['C6', 'C7', 'C8'],
        leftTop: ['B6', 'A7'],
        topRight: ['D6', 'E7', 'F8'],
      },
      D5: {
        bottom: ['D4', 'D3', 'D2', 'D1'],
        left: ['C5', 'B5', 'A5'],
        right: ['E5', 'F5', 'G5', 'H5'],
        bottomLeft: ['C4', 'B3', 'A2'],
        rightBottom: ['E4', 'F3', 'G2', 'H1'],
        top: ['D6', 'D7', 'D8'],
        leftTop: ['C6', 'B7', 'A8'],
        topRight: ['E6', 'F7', 'G8'],
      },
      E5: {
        bottom: ['E4', 'E3', 'E2', 'E1'],
        left: ['D5', 'C5', 'B5', 'A5'],
        right: ['F5', 'G5', 'H5'],
        bottomLeft: ['D4', 'C3', 'B2', 'A1'],
        rightBottom: ['F4', 'G3', 'H2'],
        top: ['E6', 'E7', 'E8'],
        leftTop: ['D6', 'C7', 'B8'],
        topRight: ['F6', 'G7', 'H8'],
      },
      F5: {
        bottom: ['F4', 'F3', 'F2', 'F1'],
        left: ['E5', 'D5', 'C5', 'B5', 'A5'],
        right: ['G5', 'H5'],
        bottomLeft: ['E4', 'D3', 'C2', 'B1'],
        rightBottom: ['G4', 'H3'],
        top: ['F6', 'F7', 'F8'],
        leftTop: ['E6', 'D7', 'C8'],
        topRight: ['G6', 'H7'],
      },
      G5: {
        bottom: ['G4', 'G3', 'G2', 'G1'],
        left: ['F5', 'E5', 'D5', 'C5', 'B5', 'A5'],
        right: ['H5'],
        bottomLeft: ['F4', 'E3', 'D2', 'C1'],
        rightBottom: ['H4'],
        top: ['G6', 'G7', 'G8'],
        leftTop: ['F6', 'E7', 'D8'],
        topRight: ['H6'],
      },
      H5: {
        bottom: ['H4', 'H3', 'H2', 'H1'],
        left: ['G5', 'F5', 'E5', 'D5', 'C5', 'B5', 'A5'],
        right: [],
        bottomLeft: ['G4', 'F3', 'E2', 'D1'],
        rightBottom: [],
        top: ['H6', 'H7', 'H8'],
        leftTop: ['G6', 'F7', 'E8'],
        topRight: [],
      },
      A4: {
        bottom: ['A3', 'A2', 'A1'],
        left: [],
        right: ['B4', 'C4', 'D4', 'E4', 'F4', 'G4', 'H4'],
        bottomLeft: [],
        rightBottom: ['B3', 'C2', 'D1'],
        top: ['A5', 'A6', 'A7', 'A8'],
        leftTop: [],
        topRight: ['B5', 'C6', 'D7', 'E8'],
      },
      B4: {
        bottom: ['B3', 'B2', 'B1'],
        left: ['A4'],
        right: ['C4', 'D4', 'E4', 'F4', 'G4', 'H4'],
        bottomLeft: ['A3'],
        rightBottom: ['C3', 'D2', 'E1'],
        top: ['B5', 'B6', 'B7', 'B8'],
        leftTop: ['A5'],
        topRight: ['C5', 'D6', 'E7', 'F8'],
      },
      C4: {
        bottom: ['C3', 'C2', 'C1'],
        left: ['B4', 'A4'],
        right: ['D4', 'E4', 'F4', 'G4', 'H4'],
        bottomLeft: ['B3', 'A2'],
        rightBottom: ['D3', 'E2', 'F1'],
        top: ['C5', 'C6', 'C7', 'C8'],
        leftTop: ['B5', 'A6'],
        topRight: ['D5', 'E6', 'F7', 'G8'],
      },
      D4: {
        bottom: ['D3', 'D2', 'D1'],
        left: ['C4', 'B4', 'A4'],
        right: ['E4', 'F4', 'G4', 'H4'],
        bottomLeft: ['C3', 'B2', 'A1'],
        rightBottom: ['E3', 'F2', 'G1'],
        top: ['D5', 'D6', 'D7', 'D8'],
        leftTop: ['C5', 'B6', 'A7'],
        topRight: ['E5', 'F6', 'G7', 'H8'],
      },
      E4: {
        bottom: ['E3', 'E2', 'E1'],
        left: ['D4', 'C4', 'B4', 'A4'],
        right: ['F4', 'G4', 'H4'],
        bottomLeft: ['D3', 'C2', 'B1'],
        rightBottom: ['F3', 'G2', 'H1'],
        top: ['E5', 'E6', 'E7', 'E8'],
        leftTop: ['D5', 'C6', 'B7', 'A8'],
        topRight: ['F5', 'G6', 'H7'],
      },
      F4: {
        bottom: ['F3', 'F2', 'F1'],
        left: ['E4', 'D4', 'C4', 'B4', 'A4'],
        right: ['G4', 'H4'],
        bottomLeft: ['E3', 'D2', 'C1'],
        rightBottom: ['G3', 'H2'],
        top: ['F5', 'F6', 'F7', 'F8'],
        leftTop: ['E5', 'D6', 'C7', 'B8'],
        topRight: ['G5', 'H6'],
      },
      G4: {
        bottom: ['G3', 'G2', 'G1'],
        left: ['F4', 'E4', 'D4', 'C4', 'B4', 'A4'],
        right: ['H4'],
        bottomLeft: ['F3', 'E2', 'D1'],
        rightBottom: ['H3'],
        top: ['G5', 'G6', 'G7', 'G8'],
        leftTop: ['F5', 'E6', 'D7', 'C8'],
        topRight: ['H5'],
      },
      H4: {
        bottom: ['H3', 'H2', 'H1'],
        left: ['G4', 'F4', 'E4', 'D4', 'C4', 'B4', 'A4'],
        right: [],
        bottomLeft: ['G3', 'F2', 'E1'],
        rightBottom: [],
        top: ['H5', 'H6', 'H7', 'H8'],
        leftTop: ['G5', 'F6', 'E7', 'D8'],
        topRight: [],
      },
      A3: {
        bottom: ['A2', 'A1'],
        left: [],
        right: ['B3', 'C3', 'D3', 'E3', 'F3', 'G3', 'H3'],
        bottomLeft: [],
        rightBottom: ['B2', 'C1'],
        top: ['A4', 'A5', 'A6', 'A7', 'A8'],
        leftTop: [],
        topRight: ['B4', 'C5', 'D6', 'E7', 'F8'],
      },
      B3: {
        bottom: ['B2', 'B1'],
        left: ['A3'],
        right: ['C3', 'D3', 'E3', 'F3', 'G3', 'H3'],
        bottomLeft: ['A2'],
        rightBottom: ['C2', 'D1'],
        top: ['B4', 'B5', 'B6', 'B7', 'B8'],
        leftTop: ['A4'],
        topRight: ['C4', 'D5', 'E6', 'F7', 'G8'],
      },
      C3: {
        bottom: ['C2', 'C1'],
        left: ['B3', 'A3'],
        right: ['D3', 'E3', 'F3', 'G3', 'H3'],
        bottomLeft: ['B2', 'A1'],
        rightBottom: ['D2', 'E1'],
        top: ['C4', 'C5', 'C6', 'C7', 'C8'],
        leftTop: ['B4', 'A5'],
        topRight: ['D4', 'E5', 'F6', 'G7', 'H8'],
      },
      D3: {
        bottom: ['D2', 'D1'],
        left: ['C3', 'B3', 'A3'],
        right: ['E3', 'F3', 'G3', 'H3'],
        bottomLeft: ['C2', 'B1'],
        rightBottom: ['E2', 'F1'],
        top: ['D4', 'D5', 'D6', 'D7', 'D8'],
        leftTop: ['C4', 'B5', 'A6'],
        topRight: ['E4', 'F5', 'G6', 'H7'],
      },
      E3: {
        bottom: ['E2', 'E1'],
        left: ['D3', 'C3', 'B3', 'A3'],
        right: ['F3', 'G3', 'H3'],
        bottomLeft: ['D2', 'C1'],
        rightBottom: ['F2', 'G1'],
        top: ['E4', 'E5', 'E6', 'E7', 'E8'],
        leftTop: ['D4', 'C5', 'B6', 'A7'],
        topRight: ['F4', 'G5', 'H6'],
      },
      F3: {
        bottom: ['F2', 'F1'],
        left: ['E3', 'D3', 'C3', 'B3', 'A3'],
        right: ['G3', 'H3'],
        bottomLeft: ['E2', 'D1'],
        rightBottom: ['G2', 'H1'],
        top: ['F4', 'F5', 'F6', 'F7', 'F8'],
        leftTop: ['E4', 'D5', 'C6', 'B7', 'A8'],
        topRight: ['G4', 'H5'],
      },
      G3: {
        bottom: ['G2', 'G1'],
        left: ['F3', 'E3', 'D3', 'C3', 'B3', 'A3'],
        right: ['H3'],
        bottomLeft: ['F2', 'E1'],
        rightBottom: ['H2'],
        top: ['G4', 'G5', 'G6', 'G7', 'G8'],
        leftTop: ['F4', 'E5', 'D6', 'C7', 'B8'],
        topRight: ['H4'],
      },
      H3: {
        bottom: ['H2', 'H1'],
        left: ['G3', 'F3', 'E3', 'D3', 'C3', 'B3', 'A3'],
        right: [],
        bottomLeft: ['G2', 'F1'],
        rightBottom: [],
        top: ['H4', 'H5', 'H6', 'H7', 'H8'],
        leftTop: ['G4', 'F5', 'E6', 'D7', 'C8'],
        topRight: [],
      },
      A2: {
        bottom: ['A1'],
        left: [],
        right: ['B2', 'C2', 'D2', 'E2', 'F2', 'G2', 'H2'],
        bottomLeft: [],
        rightBottom: ['B1'],
        top: ['A3', 'A4', 'A5', 'A6', 'A7', 'A8'],
        leftTop: [],
        topRight: ['B3', 'C4', 'D5', 'E6', 'F7', 'G8'],
      },
      B2: {
        bottom: ['B1'],
        left: ['A2'],
        right: ['C2', 'D2', 'E2', 'F2', 'G2', 'H2'],
        bottomLeft: ['A1'],
        rightBottom: ['C1'],
        top: ['B3', 'B4', 'B5', 'B6', 'B7', 'B8'],
        leftTop: ['A3'],
        topRight: ['C3', 'D4', 'E5', 'F6', 'G7', 'H8'],
      },
      C2: {
        bottom: ['C1'],
        left: ['B2', 'A2'],
        right: ['D2', 'E2', 'F2', 'G2', 'H2'],
        bottomLeft: ['B1'],
        rightBottom: ['D1'],
        top: ['C3', 'C4', 'C5', 'C6', 'C7', 'C8'],
        leftTop: ['B3', 'A4'],
        topRight: ['D3', 'E4', 'F5', 'G6', 'H7'],
      },
      D2: {
        bottom: ['D1'],
        left: ['C2', 'B2', 'A2'],
        right: ['E2', 'F2', 'G2', 'H2'],
        bottomLeft: ['C1'],
        rightBottom: ['E1'],
        top: ['D3', 'D4', 'D5', 'D6', 'D7', 'D8'],
        leftTop: ['C3', 'B4', 'A5'],
        topRight: ['E3', 'F4', 'G5', 'H6'],
      },
      E2: {
        bottom: ['E1'],
        left: ['D2', 'C2', 'B2', 'A2'],
        right: ['F2', 'G2', 'H2'],
        bottomLeft: ['D1'],
        rightBottom: ['F1'],
        top: ['E3', 'E4', 'E5', 'E6', 'E7', 'E8'],
        leftTop: ['D3', 'C4', 'B5', 'A6'],
        topRight: ['F3', 'G4', 'H5'],
      },
      F2: {
        bottom: ['F1'],
        left: ['E2', 'D2', 'C2', 'B2', 'A2'],
        right: ['G2', 'H2'],
        bottomLeft: ['E1'],
        rightBottom: ['G1'],
        top: ['F3', 'F4', 'F5', 'F6', 'F7', 'F8'],
        leftTop: ['E3', 'D4', 'C5', 'B6', 'A7'],
        topRight: ['G3', 'H4'],
      },
      G2: {
        bottom: ['G1'],
        left: ['F2', 'E2', 'D2', 'C2', 'B2', 'A2'],
        right: ['H2'],
        bottomLeft: ['F1'],
        rightBottom: ['H1'],
        top: ['G3', 'G4', 'G5', 'G6', 'G7', 'G8'],
        leftTop: ['F3', 'E4', 'D5', 'C6', 'B7', 'A8'],
        topRight: ['H3'],
      },
      H2: {
        bottom: ['H1'],
        left: ['G2', 'F2', 'E2', 'D2', 'C2', 'B2', 'A2'],
        right: [],
        bottomLeft: ['G1'],
        rightBottom: [],
        top: ['H3', 'H4', 'H5', 'H6', 'H7', 'H8'],
        leftTop: ['G3', 'F4', 'E5', 'D6', 'C7', 'B8'],
        topRight: [],
      },
      A1: {
        bottom: [],
        left: [],
        right: ['B1', 'C1', 'D1', 'E1', 'F1', 'G1', 'H1'],
        bottomLeft: [],
        rightBottom: [],
        top: ['A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8'],
        leftTop: [],
        topRight: ['B2', 'C3', 'D4', 'E5', 'F6', 'G7', 'H8'],
      },
      B1: {
        bottom: [],
        left: ['A1'],
        right: ['C1', 'D1', 'E1', 'F1', 'G1', 'H1'],
        bottomLeft: [],
        rightBottom: [],
        top: ['B2', 'B3', 'B4', 'B5', 'B6', 'B7', 'B8'],
        leftTop: ['A2'],
        topRight: ['C2', 'D3', 'E4', 'F5', 'G6', 'H7'],
      },
      C1: {
        bottom: [],
        left: ['B1', 'A1'],
        right: ['D1', 'E1', 'F1', 'G1', 'H1'],
        bottomLeft: [],
        rightBottom: [],
        top: ['C2', 'C3', 'C4', 'C5', 'C6', 'C7', 'C8'],
        leftTop: ['B2', 'A3'],
        topRight: ['D2', 'E3', 'F4', 'G5', 'H6'],
      },
      D1: {
        bottom: [],
        left: ['C1', 'B1', 'A1'],
        right: ['E1', 'F1', 'G1', 'H1'],
        bottomLeft: [],
        rightBottom: [],
        top: ['D2', 'D3', 'D4', 'D5', 'D6', 'D7', 'D8'],
        leftTop: ['C2', 'B3', 'A4'],
        topRight: ['E2', 'F3', 'G4', 'H5'],
      },
      E1: {
        bottom: [],
        left: ['D1', 'C1', 'B1', 'A1'],
        right: ['F1', 'G1', 'H1'],
        bottomLeft: [],
        rightBottom: [],
        top: ['E2', 'E3', 'E4', 'E5', 'E6', 'E7', 'E8'],
        leftTop: ['D2', 'C3', 'B4', 'A5'],
        topRight: ['F2', 'G3', 'H4'],
      },
      F1: {
        bottom: [],
        left: ['E1', 'D1', 'C1', 'B1', 'A1'],
        right: ['G1', 'H1'],
        bottomLeft: [],
        rightBottom: [],
        top: ['F2', 'F3', 'F4', 'F5', 'F6', 'F7', 'F8'],
        leftTop: ['E2', 'D3', 'C4', 'B5', 'A6'],
        topRight: ['G2', 'H3'],
      },
      G1: {
        bottom: [],
        left: ['F1', 'E1', 'D1', 'C1', 'B1', 'A1'],
        right: ['H1'],
        bottomLeft: [],
        rightBottom: [],
        top: ['G2', 'G3', 'G4', 'G5', 'G6', 'G7', 'G8'],
        leftTop: ['F2', 'E3', 'D4', 'C5', 'B6', 'A7'],
        topRight: ['H2'],
      },
      H1: {
        bottom: [],
        left: ['G1', 'F1', 'E1', 'D1', 'C1', 'B1', 'A1'],
        right: [],
        bottomLeft: [],
        rightBottom: [],
        top: ['H2', 'H3', 'H4', 'H5', 'H6', 'H7', 'H8'],
        leftTop: ['G2', 'F3', 'E4', 'D5', 'C6', 'B7', 'A8'],
        topRight: [],
      },
    },
    king: {
      A8: {
        left: [],
        right: ['B8'],
        top: [],
        bottom: ['A7'],
        leftTop: [],
        topRight: [],
        rightBottom: ['B7'],
        bottomLeft: [],
      },
      B8: {
        left: ['A8'],
        right: ['C8'],
        top: [],
        bottom: ['B7'],
        leftTop: [],
        topRight: [],
        rightBottom: ['C7'],
        bottomLeft: ['A7'],
      },
      C8: {
        left: ['B8'],
        right: ['D8'],
        top: [],
        bottom: ['C7'],
        leftTop: [],
        topRight: [],
        rightBottom: ['D7'],
        bottomLeft: ['B7'],
      },
      D8: {
        left: ['C8'],
        right: ['E8'],
        top: [],
        bottom: ['D7'],
        leftTop: [],
        topRight: [],
        rightBottom: ['E7'],
        bottomLeft: ['C7'],
      },
      E8: {
        left: ['D8'],
        right: ['F8'],
        top: [],
        bottom: ['E7'],
        leftTop: [],
        topRight: [],
        rightBottom: ['F7'],
        bottomLeft: ['D7'],
      },
      F8: {
        left: ['E8'],
        right: ['G8'],
        top: [],
        bottom: ['F7'],
        leftTop: [],
        topRight: [],
        rightBottom: ['G7'],
        bottomLeft: ['E7'],
      },
      G8: {
        left: ['F8'],
        right: ['H8'],
        top: [],
        bottom: ['G7'],
        leftTop: [],
        topRight: [],
        rightBottom: ['H7'],
        bottomLeft: ['F7'],
      },
      H8: {
        left: ['G8'],
        right: [],
        top: [],
        bottom: ['H7'],
        leftTop: [],
        topRight: [],
        rightBottom: [],
        bottomLeft: ['G7'],
      },
      A7: {
        left: [],
        right: ['B7'],
        top: ['A8'],
        bottom: ['A6'],
        leftTop: [],
        topRight: ['B8'],
        rightBottom: ['B6'],
        bottomLeft: [],
      },
      B7: {
        left: ['A7'],
        right: ['C7'],
        top: ['B8'],
        bottom: ['B6'],
        leftTop: ['A8'],
        topRight: ['C8'],
        rightBottom: ['C6'],
        bottomLeft: ['A6'],
      },
      C7: {
        left: ['B7'],
        right: ['D7'],
        top: ['C8'],
        bottom: ['C6'],
        leftTop: ['B8'],
        topRight: ['D8'],
        rightBottom: ['D6'],
        bottomLeft: ['B6'],
      },
      D7: {
        left: ['C7'],
        right: ['E7'],
        top: ['D8'],
        bottom: ['D6'],
        leftTop: ['C8'],
        topRight: ['E8'],
        rightBottom: ['E6'],
        bottomLeft: ['C6'],
      },
      E7: {
        left: ['D7'],
        right: ['F7'],
        top: ['E8'],
        bottom: ['E6'],
        leftTop: ['D8'],
        topRight: ['F8'],
        rightBottom: ['F6'],
        bottomLeft: ['D6'],
      },
      F7: {
        left: ['E7'],
        right: ['G7'],
        top: ['F8'],
        bottom: ['F6'],
        leftTop: ['E8'],
        topRight: ['G8'],
        rightBottom: ['G6'],
        bottomLeft: ['E6'],
      },
      G7: {
        left: ['F7'],
        right: ['H7'],
        top: ['G8'],
        bottom: ['G6'],
        leftTop: ['F8'],
        topRight: ['H8'],
        rightBottom: ['H6'],
        bottomLeft: ['F6'],
      },
      H7: {
        left: ['G7'],
        right: [],
        top: ['H8'],
        bottom: ['H6'],
        leftTop: ['G8'],
        topRight: [],
        rightBottom: [],
        bottomLeft: ['G6'],
      },
      A6: {
        left: [],
        right: ['B6'],
        top: ['A7'],
        bottom: ['A5'],
        leftTop: [],
        topRight: ['B7'],
        rightBottom: ['B5'],
        bottomLeft: [],
      },
      B6: {
        left: ['A6'],
        right: ['C6'],
        top: ['B7'],
        bottom: ['B5'],
        leftTop: ['A7'],
        topRight: ['C7'],
        rightBottom: ['C5'],
        bottomLeft: ['A5'],
      },
      C6: {
        left: ['B6'],
        right: ['D6'],
        top: ['C7'],
        bottom: ['C5'],
        leftTop: ['B7'],
        topRight: ['D7'],
        rightBottom: ['D5'],
        bottomLeft: ['B5'],
      },
      D6: {
        left: ['C6'],
        right: ['E6'],
        top: ['D7'],
        bottom: ['D5'],
        leftTop: ['C7'],
        topRight: ['E7'],
        rightBottom: ['E5'],
        bottomLeft: ['C5'],
      },
      E6: {
        left: ['D6'],
        right: ['F6'],
        top: ['E7'],
        bottom: ['E5'],
        leftTop: ['D7'],
        topRight: ['F7'],
        rightBottom: ['F5'],
        bottomLeft: ['D5'],
      },
      F6: {
        left: ['E6'],
        right: ['G6'],
        top: ['F7'],
        bottom: ['F5'],
        leftTop: ['E7'],
        topRight: ['G7'],
        rightBottom: ['G5'],
        bottomLeft: ['E5'],
      },
      G6: {
        left: ['F6'],
        right: ['H6'],
        top: ['G7'],
        bottom: ['G5'],
        leftTop: ['F7'],
        topRight: ['H7'],
        rightBottom: ['H5'],
        bottomLeft: ['F5'],
      },
      H6: {
        left: ['G6'],
        right: [],
        top: ['H7'],
        bottom: ['H5'],
        leftTop: ['G7'],
        topRight: [],
        rightBottom: [],
        bottomLeft: ['G5'],
      },
      A5: {
        left: [],
        right: ['B5'],
        top: ['A6'],
        bottom: ['A4'],
        leftTop: [],
        topRight: ['B6'],
        rightBottom: ['B4'],
        bottomLeft: [],
      },
      B5: {
        left: ['A5'],
        right: ['C5'],
        top: ['B6'],
        bottom: ['B4'],
        leftTop: ['A6'],
        topRight: ['C6'],
        rightBottom: ['C4'],
        bottomLeft: ['A4'],
      },
      C5: {
        left: ['B5'],
        right: ['D5'],
        top: ['C6'],
        bottom: ['C4'],
        leftTop: ['B6'],
        topRight: ['D6'],
        rightBottom: ['D4'],
        bottomLeft: ['B4'],
      },
      D5: {
        left: ['C5'],
        right: ['E5'],
        top: ['D6'],
        bottom: ['D4'],
        leftTop: ['C6'],
        topRight: ['E6'],
        rightBottom: ['E4'],
        bottomLeft: ['C4'],
      },
      E5: {
        left: ['D5'],
        right: ['F5'],
        top: ['E6'],
        bottom: ['E4'],
        leftTop: ['D6'],
        topRight: ['F6'],
        rightBottom: ['F4'],
        bottomLeft: ['D4'],
      },
      F5: {
        left: ['E5'],
        right: ['G5'],
        top: ['F6'],
        bottom: ['F4'],
        leftTop: ['E6'],
        topRight: ['G6'],
        rightBottom: ['G4'],
        bottomLeft: ['E4'],
      },
      G5: {
        left: ['F5'],
        right: ['H5'],
        top: ['G6'],
        bottom: ['G4'],
        leftTop: ['F6'],
        topRight: ['H6'],
        rightBottom: ['H4'],
        bottomLeft: ['F4'],
      },
      H5: {
        left: ['G5'],
        right: [],
        top: ['H6'],
        bottom: ['H4'],
        leftTop: ['G6'],
        topRight: [],
        rightBottom: [],
        bottomLeft: ['G4'],
      },
      A4: {
        left: [],
        right: ['B4'],
        top: ['A5'],
        bottom: ['A3'],
        leftTop: [],
        topRight: ['B5'],
        rightBottom: ['B3'],
        bottomLeft: [],
      },
      B4: {
        left: ['A4'],
        right: ['C4'],
        top: ['B5'],
        bottom: ['B3'],
        leftTop: ['A5'],
        topRight: ['C5'],
        rightBottom: ['C3'],
        bottomLeft: ['A3'],
      },
      C4: {
        left: ['B4'],
        right: ['D4'],
        top: ['C5'],
        bottom: ['C3'],
        leftTop: ['B5'],
        topRight: ['D5'],
        rightBottom: ['D3'],
        bottomLeft: ['B3'],
      },
      D4: {
        left: ['C4'],
        right: ['E4'],
        top: ['D5'],
        bottom: ['D3'],
        leftTop: ['C5'],
        topRight: ['E5'],
        rightBottom: ['E3'],
        bottomLeft: ['C3'],
      },
      E4: {
        left: ['D4'],
        right: ['F4'],
        top: ['E5'],
        bottom: ['E3'],
        leftTop: ['D5'],
        topRight: ['F5'],
        rightBottom: ['F3'],
        bottomLeft: ['D3'],
      },
      F4: {
        left: ['E4'],
        right: ['G4'],
        top: ['F5'],
        bottom: ['F3'],
        leftTop: ['E5'],
        topRight: ['G5'],
        rightBottom: ['G3'],
        bottomLeft: ['E3'],
      },
      G4: {
        left: ['F4'],
        right: ['H4'],
        top: ['G5'],
        bottom: ['G3'],
        leftTop: ['F5'],
        topRight: ['H5'],
        rightBottom: ['H3'],
        bottomLeft: ['F3'],
      },
      H4: {
        left: ['G4'],
        right: [],
        top: ['H5'],
        bottom: ['H3'],
        leftTop: ['G5'],
        topRight: [],
        rightBottom: [],
        bottomLeft: ['G3'],
      },
      A3: {
        left: [],
        right: ['B3'],
        top: ['A4'],
        bottom: ['A2'],
        leftTop: [],
        topRight: ['B4'],
        rightBottom: ['B2'],
        bottomLeft: [],
      },
      B3: {
        left: ['A3'],
        right: ['C3'],
        top: ['B4'],
        bottom: ['B2'],
        leftTop: ['A4'],
        topRight: ['C4'],
        rightBottom: ['C2'],
        bottomLeft: ['A2'],
      },
      C3: {
        left: ['B3'],
        right: ['D3'],
        top: ['C4'],
        bottom: ['C2'],
        leftTop: ['B4'],
        topRight: ['D4'],
        rightBottom: ['D2'],
        bottomLeft: ['B2'],
      },
      D3: {
        left: ['C3'],
        right: ['E3'],
        top: ['D4'],
        bottom: ['D2'],
        leftTop: ['C4'],
        topRight: ['E4'],
        rightBottom: ['E2'],
        bottomLeft: ['C2'],
      },
      E3: {
        left: ['D3'],
        right: ['F3'],
        top: ['E4'],
        bottom: ['E2'],
        leftTop: ['D4'],
        topRight: ['F4'],
        rightBottom: ['F2'],
        bottomLeft: ['D2'],
      },
      F3: {
        left: ['E3'],
        right: ['G3'],
        top: ['F4'],
        bottom: ['F2'],
        leftTop: ['E4'],
        topRight: ['G4'],
        rightBottom: ['G2'],
        bottomLeft: ['E2'],
      },
      G3: {
        left: ['F3'],
        right: ['H3'],
        top: ['G4'],
        bottom: ['G2'],
        leftTop: ['F4'],
        topRight: ['H4'],
        rightBottom: ['H2'],
        bottomLeft: ['F2'],
      },
      H3: {
        left: ['G3'],
        right: [],
        top: ['H4'],
        bottom: ['H2'],
        leftTop: ['G4'],
        topRight: [],
        rightBottom: [],
        bottomLeft: ['G2'],
      },
      A2: {
        left: [],
        right: ['B2'],
        top: ['A3'],
        bottom: ['A1'],
        leftTop: [],
        topRight: ['B3'],
        rightBottom: ['B1'],
        bottomLeft: [],
      },
      B2: {
        left: ['A2'],
        right: ['C2'],
        top: ['B3'],
        bottom: ['B1'],
        leftTop: ['A3'],
        topRight: ['C3'],
        rightBottom: ['C1'],
        bottomLeft: ['A1'],
      },
      C2: {
        left: ['B2'],
        right: ['D2'],
        top: ['C3'],
        bottom: ['C1'],
        leftTop: ['B3'],
        topRight: ['D3'],
        rightBottom: ['D1'],
        bottomLeft: ['B1'],
      },
      D2: {
        left: ['C2'],
        right: ['E2'],
        top: ['D3'],
        bottom: ['D1'],
        leftTop: ['C3'],
        topRight: ['E3'],
        rightBottom: ['E1'],
        bottomLeft: ['C1'],
      },
      E2: {
        left: ['D2'],
        right: ['F2'],
        top: ['E3'],
        bottom: ['E1'],
        leftTop: ['D3'],
        topRight: ['F3'],
        rightBottom: ['F1'],
        bottomLeft: ['D1'],
      },
      F2: {
        left: ['E2'],
        right: ['G2'],
        top: ['F3'],
        bottom: ['F1'],
        leftTop: ['E3'],
        topRight: ['G3'],
        rightBottom: ['G1'],
        bottomLeft: ['E1'],
      },
      G2: {
        left: ['F2'],
        right: ['H2'],
        top: ['G3'],
        bottom: ['G1'],
        leftTop: ['F3'],
        topRight: ['H3'],
        rightBottom: ['H1'],
        bottomLeft: ['F1'],
      },
      H2: {
        left: ['G2'],
        right: [],
        top: ['H3'],
        bottom: ['H1'],
        leftTop: ['G3'],
        topRight: [],
        rightBottom: [],
        bottomLeft: ['G1'],
      },
      A1: {
        left: [],
        right: ['B1'],
        top: ['A2'],
        bottom: [],
        leftTop: [],
        topRight: ['B2'],
        rightBottom: [],
        bottomLeft: [],
      },
      B1: {
        left: ['A1'],
        right: ['C1'],
        top: ['B2'],
        bottom: [],
        leftTop: ['A2'],
        topRight: ['C2'],
        rightBottom: [],
        bottomLeft: [],
      },
      C1: {
        left: ['B1'],
        right: ['D1'],
        top: ['C2'],
        bottom: [],
        leftTop: ['B2'],
        topRight: ['D2'],
        rightBottom: [],
        bottomLeft: [],
      },
      D1: {
        left: ['C1'],
        right: ['E1'],
        top: ['D2'],
        bottom: [],
        leftTop: ['C2'],
        topRight: ['E2'],
        rightBottom: [],
        bottomLeft: [],
      },
      E1: {
        left: ['D1'],
        right: ['F1'],
        top: ['E2'],
        bottom: [],
        leftTop: ['D2'],
        topRight: ['F2'],
        rightBottom: [],
        bottomLeft: [],
      },
      F1: {
        left: ['E1'],
        right: ['G1'],
        top: ['F2'],
        bottom: [],
        leftTop: ['E2'],
        topRight: ['G2'],
        rightBottom: [],
        bottomLeft: [],
      },
      G1: {
        left: ['F1'],
        right: ['H1'],
        top: ['G2'],
        bottom: [],
        leftTop: ['F2'],
        topRight: ['H2'],
        rightBottom: [],
        bottomLeft: [],
      },
      H1: {
        left: ['G1'],
        right: [],
        top: ['H2'],
        bottom: [],
        leftTop: ['G2'],
        topRight: [],
        rightBottom: [],
        bottomLeft: [],
      },
    },
    knight: {
      A8: {
        moves: ['C7', 'B6'],
      },
      B8: {
        moves: ['D7', 'C6', 'A6'],
      },
      C8: {
        moves: ['E7', 'A7', 'D6', 'B6'],
      },
      D8: {
        moves: ['F7', 'B7', 'E6', 'C6'],
      },
      E8: {
        moves: ['G7', 'C7', 'F6', 'D6'],
      },
      F8: {
        moves: ['H7', 'D7', 'G6', 'E6'],
      },
      G8: {
        moves: ['E7', 'H6', 'F6'],
      },
      H8: {
        moves: ['F7', 'G6'],
      },
      A7: {
        moves: ['C6', 'C8', 'B5'],
      },
      B7: {
        moves: ['D6', 'D8', 'C5', 'A5'],
      },
      C7: {
        moves: ['E6', 'E8', 'A6', 'A8', 'D5', 'B5'],
      },
      D7: {
        moves: ['F6', 'F8', 'B6', 'B8', 'E5', 'C5'],
      },
      E7: {
        moves: ['G6', 'G8', 'C6', 'C8', 'F5', 'D5'],
      },
      F7: {
        moves: ['H6', 'H8', 'D6', 'D8', 'G5', 'E5'],
      },
      G7: {
        moves: ['E6', 'E8', 'H5', 'F5'],
      },
      H7: {
        moves: ['F6', 'F8', 'G5'],
      },
      A6: {
        moves: ['C5', 'C7', 'B4', 'B8'],
      },
      B6: {
        moves: ['D5', 'D7', 'C4', 'C8', 'A4', 'A8'],
      },
      C6: {
        moves: ['E5', 'E7', 'A5', 'A7', 'D4', 'D8', 'B4', 'B8'],
      },
      D6: {
        moves: ['F5', 'F7', 'B5', 'B7', 'E4', 'E8', 'C4', 'C8'],
      },
      E6: {
        moves: ['G5', 'G7', 'C5', 'C7', 'F4', 'F8', 'D4', 'D8'],
      },
      F6: {
        moves: ['H5', 'H7', 'D5', 'D7', 'G4', 'G8', 'E4', 'E8'],
      },
      G6: {
        moves: ['E5', 'E7', 'H4', 'H8', 'F4', 'F8'],
      },
      H6: {
        moves: ['F5', 'F7', 'G4', 'G8'],
      },
      A5: {
        moves: ['C4', 'C6', 'B3', 'B7'],
      },
      B5: {
        moves: ['D4', 'D6', 'C3', 'C7', 'A3', 'A7'],
      },
      C5: {
        moves: ['E4', 'E6', 'A4', 'A6', 'D3', 'D7', 'B3', 'B7'],
      },
      D5: {
        moves: ['F4', 'F6', 'B4', 'B6', 'E3', 'E7', 'C3', 'C7'],
      },
      E5: {
        moves: ['G4', 'G6', 'C4', 'C6', 'F3', 'F7', 'D3', 'D7'],
      },
      F5: {
        moves: ['H4', 'H6', 'D4', 'D6', 'G3', 'G7', 'E3', 'E7'],
      },
      G5: {
        moves: ['E4', 'E6', 'H3', 'H7', 'F3', 'F7'],
      },
      H5: {
        moves: ['F4', 'F6', 'G3', 'G7'],
      },
      A4: {
        moves: ['C3', 'C5', 'B2', 'B6'],
      },
      B4: {
        moves: ['D3', 'D5', 'C2', 'C6', 'A2', 'A6'],
      },
      C4: {
        moves: ['E3', 'E5', 'A3', 'A5', 'D2', 'D6', 'B2', 'B6'],
      },
      D4: {
        moves: ['F3', 'F5', 'B3', 'B5', 'E2', 'E6', 'C2', 'C6'],
      },
      E4: {
        moves: ['G3', 'G5', 'C3', 'C5', 'F2', 'F6', 'D2', 'D6'],
      },
      F4: {
        moves: ['H3', 'H5', 'D3', 'D5', 'G2', 'G6', 'E2', 'E6'],
      },
      G4: {
        moves: ['E3', 'E5', 'H2', 'H6', 'F2', 'F6'],
      },
      H4: {
        moves: ['F3', 'F5', 'G2', 'G6'],
      },
      A3: {
        moves: ['C2', 'C4', 'B1', 'B5'],
      },
      B3: {
        moves: ['D2', 'D4', 'C1', 'C5', 'A1', 'A5'],
      },
      C3: {
        moves: ['E2', 'E4', 'A2', 'A4', 'D1', 'D5', 'B1', 'B5'],
      },
      D3: {
        moves: ['F2', 'F4', 'B2', 'B4', 'E1', 'E5', 'C1', 'C5'],
      },
      E3: {
        moves: ['G2', 'G4', 'C2', 'C4', 'F1', 'F5', 'D1', 'D5'],
      },
      F3: {
        moves: ['H2', 'H4', 'D2', 'D4', 'G1', 'G5', 'E1', 'E5'],
      },
      G3: {
        moves: ['E2', 'E4', 'H1', 'H5', 'F1', 'F5'],
      },
      H3: {
        moves: ['F2', 'F4', 'G1', 'G5'],
      },
      A2: {
        moves: ['C1', 'C3', 'B4'],
      },
      B2: {
        moves: ['D1', 'D3', 'C4', 'A4'],
      },
      C2: {
        moves: ['E1', 'E3', 'A1', 'A3', 'D4', 'B4'],
      },
      D2: {
        moves: ['F1', 'F3', 'B1', 'B3', 'E4', 'C4'],
      },
      E2: {
        moves: ['G1', 'G3', 'C1', 'C3', 'F4', 'D4'],
      },
      F2: {
        moves: ['H1', 'H3', 'D1', 'D3', 'G4', 'E4'],
      },
      G2: {
        moves: ['E1', 'E3', 'H4', 'F4'],
      },
      H2: {
        moves: ['F1', 'F3', 'G4'],
      },
      A1: {
        moves: ['C2', 'B3'],
      },
      B1: {
        moves: ['D2', 'C3', 'A3'],
      },
      C1: {
        moves: ['E2', 'A2', 'D3', 'B3'],
      },
      D1: {
        moves: ['F2', 'B2', 'E3', 'C3'],
      },
      E1: {
        moves: ['G2', 'C2', 'F3', 'D3'],
      },
      F1: {
        moves: ['H2', 'D2', 'G3', 'E3'],
      },
      G1: {
        moves: ['E2', 'H3', 'F3'],
      },
      H1: {
        moves: ['F2', 'G3'],
      },
    },
  };

  constructor() {}
}
