import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class UtilsService {
  public boardStatus = [
    { name: 'A8', occupiedBy: null, occupiedByType: null },
    { name: 'B8', occupiedBy: null, occupiedByType: null },
    { name: 'C8', occupiedBy: null, occupiedByType: null },
    { name: 'D8', occupiedBy: null, occupiedByType: null },
    { name: 'E8', occupiedBy: null, occupiedByType: null },
    { name: 'F8', occupiedBy: null, occupiedByType: null },
    { name: 'G8', occupiedBy: null, occupiedByType: null },
    { name: 'H8', occupiedBy: null, occupiedByType: null },
    { name: 'A7', occupiedBy: null, occupiedByType: null },
    { name: 'B7', occupiedBy: null, occupiedByType: null },
    { name: 'C7', occupiedBy: null, occupiedByType: null },
    { name: 'D7', occupiedBy: null, occupiedByType: null },
    { name: 'E7', occupiedBy: null, occupiedByType: null },
    { name: 'F7', occupiedBy: null, occupiedByType: null },
    { name: 'G7', occupiedBy: null, occupiedByType: null },
    { name: 'H7', occupiedBy: null, occupiedByType: null },
    { name: 'A6', occupiedBy: null, occupiedByType: null },
    { name: 'B6', occupiedBy: null, occupiedByType: null },
    { name: 'C6', occupiedBy: null, occupiedByType: null },
    { name: 'D6', occupiedBy: null, occupiedByType: null },
    { name: 'E6', occupiedBy: null, occupiedByType: null },
    { name: 'F6', occupiedBy: null, occupiedByType: null },
    { name: 'G6', occupiedBy: null, occupiedByType: null },
    { name: 'H6', occupiedBy: null, occupiedByType: null },
    { name: 'A5', occupiedBy: null, occupiedByType: null },
    { name: 'B5', occupiedBy: null, occupiedByType: null },
    { name: 'C5', occupiedBy: null, occupiedByType: null },
    { name: 'D5', occupiedBy: null, occupiedByType: null },
    { name: 'E5', occupiedBy: null, occupiedByType: null },
    { name: 'F5', occupiedBy: null, occupiedByType: null },
    { name: 'G5', occupiedBy: null, occupiedByType: null },
    { name: 'H5', occupiedBy: null, occupiedByType: null },
    { name: 'A4', occupiedBy: null, occupiedByType: null },
    { name: 'B4', occupiedBy: null, occupiedByType: null },
    { name: 'C4', occupiedBy: null, occupiedByType: null },
    { name: 'D4', occupiedBy: null, occupiedByType: null },
    { name: 'E4', occupiedBy: null, occupiedByType: null },
    { name: 'F4', occupiedBy: null, occupiedByType: null },
    { name: 'G4', occupiedBy: null, occupiedByType: null },
    { name: 'H4', occupiedBy: null, occupiedByType: null },
    { name: 'A3', occupiedBy: null, occupiedByType: null },
    { name: 'B3', occupiedBy: null, occupiedByType: null },
    { name: 'C3', occupiedBy: null, occupiedByType: null },
    { name: 'D3', occupiedBy: null, occupiedByType: null },
    { name: 'E3', occupiedBy: null, occupiedByType: null },
    { name: 'F3', occupiedBy: null, occupiedByType: null },
    { name: 'G3', occupiedBy: null, occupiedByType: null },
    { name: 'H3', occupiedBy: null, occupiedByType: null },
    { name: 'A2', occupiedBy: null, occupiedByType: null },
    { name: 'B2', occupiedBy: null, occupiedByType: null },
    { name: 'C2', occupiedBy: null, occupiedByType: null },
    { name: 'D2', occupiedBy: null, occupiedByType: null },
    { name: 'E2', occupiedBy: null, occupiedByType: null },
    { name: 'F2', occupiedBy: null, occupiedByType: null },
    { name: 'G2', occupiedBy: null, occupiedByType: null },
    { name: 'H2', occupiedBy: null, occupiedByType: null },
    { name: 'A1', occupiedBy: null, occupiedByType: null },
    { name: 'B1', occupiedBy: null, occupiedByType: null },
    { name: 'C1', occupiedBy: null, occupiedByType: null },
    { name: 'D1', occupiedBy: null, occupiedByType: null },
    { name: 'E1', occupiedBy: null, occupiedByType: null },
    { name: 'F1', occupiedBy: null, occupiedByType: null },
    { name: 'G1', occupiedBy: null, occupiedByType: null },
    { name: 'H1', occupiedBy: null, occupiedByType: null },
  ];

  boardAsWhite = [
    'A8',
    'B8',
    'C8',
    'D8',
    'E8',
    'F8',
    'G8',
    'H8',
    'A7',
    'B7',
    'C7',
    'D7',
    'E7',
    'F7',
    'G7',
    'H7',
    'A6',
    'B6',
    'C6',
    'D6',
    'E6',
    'F6',
    'G6',
    'H6',
    'A5',
    'B5',
    'C5',
    'D5',
    'E5',
    'F5',
    'G5',
    'H5',
    'A4',
    'B4',
    'C4',
    'D4',
    'E4',
    'F4',
    'G4',
    'H4',
    'A3',
    'B3',
    'C3',
    'D3',
    'E3',
    'F3',
    'G3',
    'H3',
    'A2',
    'B2',
    'C2',
    'D2',
    'E2',
    'F2',
    'G2',
    'H2',
    'A1',
    'B1',
    'C1',
    'D1',
    'E1',
    'F1',
    'G1',
    'H1',
  ];

  constructor() {}
}
